#!/usr/bin/env bash
#
# l4d2-run.sh — launch L4D2 ZoneMod instance #N.
#
# One template launches the whole fleet: it auto-generates the per-instance
# config (so there are no per-server files to maintain by hand) and starts
# srcds on a derived port.
#
#   game port  = PORT_BASE + N        (e.g. PORT_BASE=6032 → server #1 = 6033/udp)
#   in-game name = "$BASE_NAME #N"
#
# Used as the ExecStart of the systemd template unit `l4d2@.service`.
#
set -euo pipefail

N="${1:?usage: l4d2-run.sh <instance-number>}"

# shellcheck source=/dev/null
source /etc/l4d2-fleet/fleet.env

PORT=$(( PORT_BASE + N ))
CFG="server_${N}.cfg"

# Auto-generate this instance's config: exec the shared base, then override the
# hostname. (Setting hostname via +hostname on the CLI is unreliable — Source
# truncates it at the first space — so it must live in a quoted cfg line.)
cat > "${INSTALL_DIR}/left4dead2/cfg/${CFG}" <<EOF
// Auto-generated by l4d2-run.sh — server #${N}. Do not edit by hand.
exec server.cfg
hostname "${BASE_NAME} #${N}"
EOF

cd "${INSTALL_DIR}"
exec ./srcds_run -game left4dead2 -norestart -port "${PORT}" \
  +sv_clockcorrection_msecs 25 -timeout 10 -tickrate "${TICKRATE:-100}" \
  +mp_gamemode "${GAMEMODE:-versus}" +map "${START_MAP:-c1m1_hotel}" \
  -maxplayers "${MAXPLAYERS:-32}" +servercfgfile "${CFG}"
