---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: restart l4d2-exporter
  ansible.builtin.systemd:
    name: l4d2-exporter
    state: restarted

- name: restart grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted

- name: restart loki
  ansible.builtin.systemd:
    name: loki
    state: restarted

- name: restart promtail
  ansible.builtin.systemd:
    name: promtail
    state: restarted

- name: restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
